using System;
using System.Net;
using System.Threading;
using System.Threading.Tasks;
using Application.Errors;
using Domain;
using MediatR;
using Persistence;

namespace Application.Activities
{
    public class Details
    {
        public class Query : IRequest<Activity>
        {
            public Guid Id { get; set; }
        }

        public class Handler : IRequestHandler<Query, Activity>
        // ctrl + . generate constructor -> autogenerated code bellow
        // ctrl + . on IRequestHandler and generate interface -> autogenerated code bellow


        {
            private readonly DataContext _context;
            // function handler will consume value of context of type DataContext
            public Handler(DataContext context)
            // ctrl + . -> using Persistence
            // ctrl + .  on context-> initialize field from parameter 
            {
                _context = context;
            }

            public async Task<Activity> Handle(Query request, CancellationToken cancellationToken)
            {
                var activity = await _context.Activities.FindAsync(request.Id);

                if (activity == null)
                    throw new RestException(HttpStatusCode.NotFound, new { activity = "Not found" });

                return activity;
            }
        }
    }
}